---
title: "Dissimilarity-Overlap analysis"
author: "Leo Lahti `r Sys.Date()`"
bibliography: 
- bibliography.bib
output:
  BiocStyle::html_document:
    number_sections: no
    toc: yes
    toc_depth: 4
    toc_float: true
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    use_bookdown: false
    highlight: haddock
   
---
<!--
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{microbiome tutorial - doc}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}  
-->

```{r setup, message = FALSE, warning = FALSE, results = 'hide'}
#library("devtools")
#install_github("microbiome/microbiome")
```

# Dissimilarity-Overlap analysis

This page provides an example of running the dissimilarity-overlap analysis as proposed in Bashan, A., Gibson, T., Friedman, J. et al. Universality of human microbial dynamics. Nature 534, 259–262 (2016). [DOI:10.1038/nature18301](https://doi.org/10.1038/nature18301).


Load example data:

```{r doc_data, warning=FALSE, message=FALSE}
# Dissimilarity-Overlap analysis
library(microbiome)
data(atlas1006)
```

Estimate the overlap and dissimilarity quantities:

```{r doc_quantities, warning=FALSE, message=FALSE}
# Dissimilarity
d <- phyloseq::distance(transform(atlas1006), "jsd", parallel=TRUE)

# Overlap
o <- overlap(atlas1006, detection = 0.2/100)
```

```{r doc_compare, warning=FALSE, message=FALSE}
# Compare
dvec <- d[lower.tri(d)]
ovec <- o[lower.tri(o)]

# Assess rough correlation
cc <- cor(dvec, ovec, method = "spearman", use = "pairwise.complete.obs")

# Scatterplot
plot(dvec, ovec, pch = ".", main = paste("Spearman rho", round(cc, 2)), las = 1, xlab = "Dissimilarity (Jensen-Shannon)", ylab = "Overlap")

#p <- data.frame(D = dvec, O = ovec) %>%
#  ggplot(aes(x = D, y = O)) +
#  geom_hex()
```







